### ISSUE TITLE
values=meaning mapping: warn re spaces flanking the equal sign

### ISSUE THREAD

**Issue by DanielEWeeks** [lwheinsberg/dbGaPCheckup#13]
Not sure if it is absolutely required or not by dbGaP, but as all the examples of the values=meaning mappings in the dbGaP Submission Guide have no spaces flanking the equal sign (e.g. `1=Male`), I would favor alerting our users when there is a space (e.g. `1= Male` or `1 =Male`, etc.).

Looks like dbGaPCheckup currently does not alert our users when there is a space.

**Comment by lwheinsberg** [comment]
Strange ... this is captured by `values_check`. Why is this not working correctly?

Oh I see the problem. I corrected by changing: 

```
trouble_rows <- c(unique(trouble_rows1, trouble_rows2))
```

to 

```
trouble_rows <- unique(c(trouble_rows1, trouble_rows2))
```
