### ISSUE TITLE
name_correct behavior when not needed

### ISSUE THREAD

**Issue by DanielEWeeks** [lwheinsberg/dbGaPCheckup#14]
If I mistakenly run `name_correct` when it is not needed (e.g., the names match and are in the same order between the two files), it still prints out the message: "CORRECTED ERROR: the variable names differ between the data dictionary and the data" even though the names do not actually differ.

This is the output I get when the variable names do not differ between the data dictionary and the data:

```
DS.data_updated <- name_correct(DD.dict, DS.data)
#> $Message
#> [1] "CORRECTED ERROR: the variable names differ between the data dictionary and the data. **ALERT** Renaming variable(s) to match those listed in the data dictionary."
#> 
#> $Information
#> # A tibble: 1 × 3
#>   Data                   Dict                New.Data      
#>   <chr>                  <chr>               <chr>         
#> 1 "Original data name: " "Dictionary name: " New data name:
```

**Comment by lwheinsberg** [comment]
This issue has been corrected. Now, when a user runs `name_correct` when it is not needed, the original data frame will be returned along with an message that states "No name discrepancies detected; original data frame returned."
