### ISSUE TITLE
type_check error is not specific

### ISSUE THREAD

**Issue by pbuendia** [lwheinsberg/dbGaPCheckup#15]
We wrongly thought this is the type_check error as the error is not specific: When a column has values looking like decimal values like the ICD9 identifiers, then the data dictionary is required to have Type= "decimal" although the identifiers are not decimals, they are strings.  Can this be fixed?

**Comment by pbuendia** [comment]
That was not the issue! It does accept "string" just fine, but because the error is not specific we did not see it was because of a typo in another row.

**Comment by lwheinsberg** [comment]
Thanks for raising the potential issue. Glad everything is working OK! And excited to hear that you are using the package! Hope it is helpful.
