### ISSUE TITLE
values_check bug if DD.dict has blank column names after 'VALUES' column

### ISSUE THREAD

**Issue by DanielEWeeks** [lwheinsberg/dbGaPCheckup#3]
In my `DD.dict`, I set the column names after the `VALUES` column to the blank string, as that is what is expected by dbGaP:

> The VALUES header must be the last column header and should appear ONLY in the column above the FIRST encoded value that is listed. The remaining value column header cells should be left blank. 

```
> names(DD.dict)
 [1] "VARNAME"         "VARDESC"         "DOCFILE"         "TYPE"           
 [5] "UNITS"           "MIN"             "MAX"             "RESOLUTION"     
 [9] "COMMENT1"        "COMMENT2"        "VARIABLE_SOURCE" "VARIABLE_TERM"  
[13] "UNIQUEKEY"       "COLLINTERVAL"    "ORDER"           "VALUES"         
[17] ""                ""                ""                ""               
[21] ""                ""                ""                ""               
[25] ""                ""                ""                ""               
[29] ""                ""                ""                ""               
[33] ""                ""                ""                ""               
[37] ""                ""                ""                ""               
[41] ""               
```

However, that causes `values_check` to die with this error message:

```
> values_check(DD.dict, verbose = FALSE)
Error in `DD.dict[!is.na(DD.dict[col]) & !grepl("=", unlist(DD.dict[col])), c("VARNAME",
    names(DD.dict)[col])]`:
! Can't subset columns with `c("VARNAME", names(DD.dict)[col])`.
✖ Subscript `c("VARNAME", names(DD.dict)[col])` can't contain the empty string.
✖ It has an empty string at location 2.
Run `rlang::last_trace()` to see where the error occurred.
```

Looks to me like this line in `values_check` is not working as soon as `col` is set to the number of a `DD.dict` column that has a non-unique `""` empty string column name:

```
        values.check <- (dim(DD.dict[!is.na(DD.dict[col]) & 
          !grepl("=", unlist(DD.dict[col])), c("VARNAME", 
          names(DD.dict)[col])])[1] == 0)
```

Perhaps we didn't encounter this before because in the example in the vignette, it looks like the columns after the `VALUES` column were assigned non-empty names like

```
…18  …19  …20
```

when it was read in, as we point out in the vignette:

> The VALUES header must be the last column header and should appear ONLY in the column above the FIRST encoded value that is listed. The remaining value column header cells should be left blank. (Note that when we read in our example data set with blank column names after VALUES, R automatically fills in the column names with the column number (e.g., ...18, ...19, etc.). This is acceptable for the package level checks, but not allowable for the files that are submitted to dbGaP.)

So it looks like `values_check` is assuming every column in the `DD.dict` file has a non-blank unique name.

But if someone wants to set their `DD.dict` file up with blank column names after `VALUES`, our code should be able to process such a file.  Could have `values_check` fill in any blank column names with unique names in a temporary copy of the `DD.dict` file before carrying out its checks. 

Also, I originally had my file set up with non-blank names (`VALUES`, `VALUES1`, `VALUES2`, ...), but that got flagged as an error by `misc_format_check`:

```
$Information
# A tibble: 29 × 6
   check.name check.description             check.status details col.name correct
   <chr>      <chr>                         <chr>        <lgl>   <chr>    <lgl>  
 1 Check 1    Empty variable name check     Passed       NA      NA       NA     
 2 Check 2    Duplicate variable name check Passed       NA      NA       NA     
 3 Check 3    Check for use of `dbgap` in … Passed       NA      NA       NA     
 4 Check 4    Duplicate dictionary column … Passed       NA      NA       NA     
 5 Check 5    Column names after `VALUES` … Failed       NA      VALUES1  FALSE  
 6 Check 5    Column names after `VALUES` … Failed       NA      VALUES2  FALSE  
 7 Check 5    Column names after `VALUES` … Failed       NA      VALUES3  FALSE  
 8 Check 5    Column names after `VALUES` … Failed       NA      VALUES4  FALSE  
 9 Check 5    Column names after `VALUES` … Failed       NA      VALUES5  FALSE  
10 Check 5    Column names after `VALUES` … Failed       NA      VALUES6  FALSE  
# ℹ 19 more rows
```

**Comment by lwheinsberg** [comment]
On 8-10-2023, Dan adjusted `values_check` to temporarily create dummy names for blank-named columns beyond VALUES.
