### ISSUE TITLE
minmax_check bug when SUBJECT_ID is a character vector

### ISSUE THREAD

**Issue by DanielEWeeks** [lwheinsberg/dbGaPCheckup#4]
If `SUBJECT_ID` is a character vector and `non.NA.missing.codes` is a vector of integers, then `minmax_check` dies with this error message:

```
Browse[2]> 
debug: for (value in na.omit(non.NA.missing.codes)) {
    dataset_na <- dataset_na %>% mutate(across(everything(), 
        ~na_if(.x, value)))
}
Browse[2]> 
debug: dataset_na <- dataset_na %>% mutate(across(everything(), ~na_if(.x, 
    value)))
Browse[2]> 
Error in `mutate()`:
ℹ In argument: `across(everything(), ~na_if(.x, value))`.
Caused by error in `across()`:
! Can't compute column `SUBJECT_ID`.
Caused by error in `na_if()`:
! Can't convert `y` <double> to match type of `x` <character>.
Run `rlang::last_trace()` to see where the error occurred.
```

The problem appears to appear inside the `na_if` function at this line:

```
Browse[2]> 
debug: y <- vec_cast(x = y, to = x, x_arg = "y", to_arg = "x")
Browse[2]> head(x)
[1] "SG0090" "SG0175" "SG0176" "SG0180" "SG0189" "SG0190"
Browse[2]> head(y)
[1] -3333
```

But I really don't understand why the error is being generated, as `y` is a double, and, as such, we should be apply `vec_cast` to convert it to match the type of `x`, which is character.

**Minimal working example:**

```
> y <- -3333; class(y)
[1] "numeric"
> x <- "SG000"; class(x)
[1] "character"
> vec_cast(x = y, to = x, x_arg = "y", to_arg = "x")
Error:
! Can't convert `y` <double> to match type of `x` <character>.
Run `rlang::last_trace()` to see where the error occurred.
```

or

```
> na_if("SG000", -3333)
Error in `na_if()`:
! Can't convert `y` <double> to match type of `x` <character>.
Run `rlang::last_trace()` to see where the error occurred.
```

-------

**na_if man page**

<h3 style="color: rgb(89, 89, 89); font-family: &quot;SF Pro Text&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Usage</h3><div class="code-toolbar" style="position: relative; color: rgb(0, 0, 0); font-family: &quot;SF Pro Text&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 13.3333px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><pre class="language-r" tabindex="0" style="color: black; background: none; text-shadow: white 0px 1px; font-family: Courier, monospace; font-size: 1em; text-align: left; white-space: pre; word-spacing: normal; word-break: normal; overflow-wrap: normal; line-height: 1.5; tab-size: 4; hyphens: none; overflow: auto;"><code class="language-r" style="color: black; background: none; text-shadow: white 0px 1px; font-family: Courier, monospace; font-size: 1em; text-align: left; white-space: pre; word-spacing: normal; word-break: normal; overflow-wrap: normal; line-height: 1.5; tab-size: 4; hyphens: none;">na_if<span class="token punctuation" style="color: rgb(153, 153, 153);">(</span>x<span class="token punctuation" style="color: rgb(153, 153, 153);">,</span> y<span class="token punctuation" style="color: rgb(153, 153, 153);">)</span>
</code></pre><div class="toolbar" style="position: absolute; z-index: 10; top: 0.3em; right: 0.2em; transition: opacity 0.3s ease-in-out 0s; opacity: 0;"></div></div><h3 style="color: rgb(89, 89, 89); font-family: &quot;SF Pro Text&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Arguments</h3>

x | Vector to modify
-- | --
y | Value or vector to compare against. When x and y are equal, the value in x will be replaced with NA.y is cast to the type of x before comparison.y is recycled to the size of x before comparison. This means that y can be a vector with the same size as x, but most of the time this will be a single value.

Usage
na_if(x, y)
Arguments
x	
Vector to modify

y	
Value or vector to compare against. When x and y are equal, the value in x will be replaced with NA.

y is cast to the type of x before comparison.

y is [recycled](http://127.0.0.1:40329/help/library/vctrs/help/vector_recycling_rules) to the size of x before comparison. This means that y can be a vector with the same size as x, but most of the time this will be a single value.

------

Maybe instead of using `na_if`, we could use `naniar::replace_with_na()`

https://cran.r-project.org/web/packages/naniar/vignettes/replace-with-na.html

**Comment by DanielEWeeks** [comment]
I asked about why `na_if` was doing what it was doing on Mastodon, and got this response:

> It's using {vctrs} under the hood for coercion so follows the rules they set out in https://vctrs.r-lib.org/reference/theory-faq-coercion.html. It may be worth raising an issue to get this emphasized in the documentation

https://fosstodon.org/@_TimTaylor/110826241112392137

If I understand these rules, `na_if` is only happy if the class of the missing value code matches that of the vector being checked for missing values.   So if the vector is numeric, it needs to be compared against a numeric missing value code, and if the vector is a character vector, it needs to be compared against a character missing value code.

For example,

```
> na_if("ID", -3333)
Error in `na_if()`:
! Can't convert `y` <double> to match type of `x` <character>.
Run `rlang::last_trace()` to see where the error occurred.
> na_if("ID", "-3333")
[1] "ID"
> na_if( 1, "-3333")
Error in `na_if()`:
! Can't convert `y` <character> to match type of `x` <double>.
Run `rlang::last_trace()` to see where the error occurred.
> na_if( 1, -3333)
[1] 1
```

--------

Looks like the command `replace_with_na_all` from the `nanair` package might work as desired - here we test it with a simple data frame where one column is numeric and the other is character. 

_"This function takes a dataframe and replaces all values that meet the condition specified as an NA value"_

```
> non.NA.missing.codes
[1] -3333 -4444 -9999 -5555 -6666 -7777 -8888
> a
      a     b
1 -3333     A
2     1 -3333
> lapply(a, class)
$a
[1] "numeric"

$b
[1] "character"

> replace_with_na_all(a, condition = ~.x %in% non.NA.missing.codes)
# A tibble: 2 × 2
      a b    
  <dbl> <chr>
1    NA A    
2     1 NA   
```

**Comment by lwheinsberg** [comment]
Dan resolved this 8-10-2023 by using the command `replace_with_na_all` from the nanair package. Additional documentation in entry above.
