### ISSUE TITLE
Make `complete_check` more robust to errors

### ISSUE THREAD

**Issue by DanielEWeeks** [lwheinsberg/dbGaPCheckup#6]
I think it might be helpful to make `complete_check` more robust to failure of the individual components.

To do that, we'd wrap each call in a `try`.  

For example, if `pkg_field_check` crashes in an error, none of the subsequent checks are run.

```
report <- bind_rows(report, pkg_field_check(DD_dict, DS_data, 
        verbose = FALSE))
```

But if we wrapped `pkg_field_check(DD_dict, DS_data, verbose = FALSE)` in a `try` we could presumably record that it failed to successfully run in the `report` table and go on to attempt to run the rest of the checks. 

See http://adv-r.had.co.nz/Exceptions-Debugging.html#condition-handling

**Comment by lwheinsberg** [comment]
I have created a new temporary version of `complete_check()` for discussion with @DanielEWeeks. The new function is called `complete_check2()` and uses tryCatch in an attempt to make this function more robust as shown below: 

```
# Note: Edits made in response to issue #6; ChatGPT used for help in creating the structure of the tryCatch solution
tryCatch({
    field_result <- field_check(DD_dict, verbose = FALSE)
    report <- bind_rows(report, field_result)
  }, error = function(e) {
    message("field_check encountered an error:", e$message)
    report <- bind_rows(report, data.frame(
      Time = Sys.time(),
      Name = "field_check",
      Status = "Error",
      Message = paste("field_check encountered an error:", e$message),
      Information = NA
    ))
  })
  
  # Check 2: pkg_field_check
  #report <- bind_rows(report, pkg_field_check(DD_dict, DS_data, verbose=FALSE))
  tryCatch({
    pkg_field_result <- pkg_field_check(DD_dict, DS_data, verbose = FALSE)
    report <- bind_rows(report, pkg_field_result)
  }, error = function(e) {
    message("pkg_field_check encountered an error:", e$message)
    report <- bind_rows(report, data.frame(
      Time = Sys.time(),
      Name = "pkg_field_check",
      Status = "Error",
      Message = paste("pkg_field_check encountered an error:", e$message),
      Information = NA
    ))
  })
```

In testing it on our example data sets, I get the same results as the original function, with the only difference between time stamps. 

```
# Compare complete_check and complete_check2 to make sure they produce the same results
> results <- complete_check(DD.dict.D, DS.data.D, non.NA.missing.codes=c(-9999, -4444))
> results2 <- complete_check2(DD.dict.D, DS.data.D, non.NA.missing.codes=c(-9999, -4444))
> identical(results, results2)
[1] FALSE

# Compare results and results2
> # Compare results and results2
> differences <- all.equal(results, results2)
> 
> # Check if there are differences
> if (is.logical(differences)) {
+     if (differences) {
+         print("The objects are nearly identical.")
+     } else {
+         print("The objects have differences:")
+         print(differences)
+     }
+ } else {
+     print("The objects have differences:")
+     print(differences)
+ }
[1] "The objects have differences:"
[1] "Component “Time”: Mean absolute difference: 4.729441"
```

Right now, I am having trouble coming up with an example to test that contains errors that we don't already account for in the functions to see how this will behave. Wondering if Dan either (1) has any ideas for potential errors we could introduce into one of our example data sets and/or (2) could look over the new `complete_check2` to see what he thinks about its robustness. 

Once I discuss this with Dan and we settle on a solution, my plan is to completely replace `complete_check` with the hopefully more robust `complete_check2`.  

-----------------------------------------


Some notes about `try()` vs. `tryCatch()`: 

try(): a simple error-handling function used to attempt the execution of an expression and capture any errors or warnings that occur during the execution; returns an object of class "try-error".

tryCatch(): more flexible and powerful allowing users to specify different actions for different types of conditions (e.g., errors, warnings, messages, etc.); returns the result of the expression or a specified action depending on the condition that occurs.

**Comment by lwheinsberg** [comment]
I have made a few more changes to this function (e.g., <<- vs. <-, creating report as a tibble(), etc.) to get this to work properly in the face of an unaccounted for error tested by calling the following: 

```
field_check2 <- function() {stop("unexpected error")}
```

I also reverted trial `complete_check2()` back to `complete_check()`.

This issue has now been resolved.
