### ISSUE TITLE
`misc_format_check` allows for non-blank extra `VALUES` names

### ISSUE THREAD

**Issue by DanielEWeeks** [lwheinsberg/dbGaPCheckup#7]
Here,

```
misc_format_check.R:        correct <- isTRUE(startsWith(col.name, "..."))
```

we are not forcing the user to use blank names for the extra `VALUES` columns in the `DD.dict` in the _internal_ R version of the `DD.dict`, but maybe this is OK if the names are blank in the original Excel sheet and the Excel sheet is read in the way we are reading them in with `readxl::read_xlsx`.

But if someone writes out the `DD.dict` from R without being aware of this issue, then I think their resulting written-out file will have non-blank names for the extra `VALUES` columns.

**Comment by lwheinsberg** [comment]
Discussed with Dan. Will add a Warning note to misc_format_check that alerts the user that they read in a data set and R automatically filled in column names after VALUES. Alert user that this is allowed by the package, but it is NOT allowed by dbGaP.

**Comment by lwheinsberg** [comment]
Check number 5 within this function has been adjusted to return a WARNING that alerts users if they read in a data set and R automatically fills in column names after VALUES. The warning, and a new details section of the documentation, explains to users that this is allowed by the package, but it is NOT allowed by dbGaP.
