### ISSUE TITLE
NA_check

### ISSUE THREAD

**Issue by DanielEWeeks** [lwheinsberg/dbGaPCheckup#8]
`NA_check` returns this message:

"Error: your data set contains NA values with no encoded NA value=meaning found. If you choose to retain NA values, NA must be specified as a missing value code in VALUES fields as a dbGaP requirement."

even in a case where the data set does contain some NA values and we do have a VALUE=MEANING mapping of "NA=N/A" defined.

Looks like `NA_check` is trying to check if there is at least one NA mapped to at least one of the `VALUE`s using this code:

```
        if (sum(is.na(DS.data)) > 0) {
            tb <- value_meaning_table(DD.dict)
            non.NA.missing.codes <- NULL      # Why is this line here?
            if (NA %in% tb$VALUE) {
                chk <- TRUE
            }
            else {
                chk <- FALSE
            }
        }
```

But when `tb$VALUE` contains "NA" as a character string instead of as a native `NA`  this code doesn't work as intended.

For example, 

```
> unique(sort(tb$VALUE))
 [1] "-1"       "-12000"   "-2"       "-3"       "-3333"    "-4444"    "-5555"   
 [8] "-60000"   "-6666"    "-7777"    "-8888"    "-9999"    "0"        "1"       
[15] "10"       "11"       "12"       "13"       "14"       "15"       "16"      
[22] "17"       "18"       "2"        "3"        "4"        "45"       "5"       
[29] "6"        "7"        "8"        "9"        "96"       "99"       "cool_dry"
[36] "hot_wet"  "NA" 
> NA %in% tb$VALUE
[1] FALSE
> "NA" %in% tb$VALUE
[1] TRUE
```

In the data frame returned by the `value_meaning_table` function, the `VALUE` column is always a character vector (because we use the `separate` term to split the VALUE=MEANING string into its VALUE and MEANING components.

So I think the fix is to change this line from this

```
            if (NA %in% tb$VALUE) {
```

to

```
            if ("NA" %in% tb$VALUE) {
```

To test that the `NA_check` test is passed when the data contains some NA values but the dictionary contains a mapping of NA to a meaning, we should construct another example data set that has those conditions.  The current 'pass' example for `NA_check` is on `ExampleA`, which contains no NA values.

**Question 1**: This is a general check that looks at the whole data frame.  So I think it could pass if, for example, there were three variables that contains NA values, but only one of them had an NA=meaning VALUE=MEANING mapping.  So does some other function check at the individual variable level?

**Question 2**: If `NA` is one of our chosen missing value codes, does the `non.NA.missing.codes` option work properly?  For example, in `missing_value_check`, we omit the NA value from the list of valid missing value codes: 

```
codes <- unique(na.omit(non.NA.missing.codes))
```

**Comment by lwheinsberg** [comment]
The suggested edit, changing: 

`if (NA %in% tb$VALUE) {`

to

`if ("NA" %in% tb$VALUE) {`

has been made. This edit now corrects the issue originally raised. 

This has been tested on new `ExampleS` which intentionally introduces the aforementioned error. 

-------------------

Following up on the two questions raised: 

> Question 1: This is a general check that looks at the whole data frame. So I think it could pass if, for example, there were three variables that contains NA values, but only one of them had an NA=meaning VALUE=MEANING mapping. So does some other function check at the individual variable level?

Correct - this is a general check that looks at the whole data frame, so it can pass if only one variable contains NA=missing in its value code. The `missing_value_check` was designed to catch variable-level errors, but it currently does so for only items listed as a `non.NA.missing.codes`. 

To address this issue, I modified `missing_value_check` to include any `non.NA.missing.codes` provided by the user AS WELL AS NA values. 

> Question 2: If NA is one of our chosen missing value codes, does the non.NA.missing.codes option work properly? For example, in missing_value_check, we omit the NA value from the list of valid missing value codes:
> 
> codes <- unique(na.omit(non.NA.missing.codes))

This has been addressed under Question 1.
